baseURL: "https://saaste.net/"
defaultContentLanguage: fi
enableRobotsTXT: true
languageCode: fi
theme: "saaste"
timeZone: "Europe/Helsinki"
title: "saaste.net"
pluralizelisttitles: false
titleCaseStyle: firstupper

languages:
  fi:
    languageCode: fi
    languageDirection: ltr
    params:
      reading_speed: 250

menus:
    main:
      - name: "tietoa"
        url: "/tietoa/"
        weight: 1
      - name: "blogi"
        url: "/blogi/"
        weight: 2
      - name: "nyt"
        url: "/nyt/"
        weight: 3
      - name: "muuta"
        url: "/muuta/"
        weight: 4
      - name: "haku"
        url: "/haku/"
        weight: 5

    bottom:
      - name: "Tilaa"
        url: "/tilaa"
        weight: 2
      - name: "Muutosloki"
        url: "/muutosloki"
        weight: 3

taxonomies:
  aiheet: "aiheet"
  sarjat: "sarjat"

pagination:
  pageSize: 10

